
name: Code coverage

on:
  push:
    branches: ["master"]
    

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run tests
        env:
          TESTNET_ENDPOINT: https://testnet.hashio.io/api
          TESTNET_OPERATOR_PRIVATE_KEY: 0xd14cfce33a5056431635f8dcd0b685161524ea81ceeada09fc2b66c15444ca31
          LOCAL_OPERATOR_PRIVATE_KEY: 0xd14cfce33a5056431635f8dcd0b685161524ea81ceeada09fc2b66c15444ca31
        run: |
          npm i
          npm run coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          verbose: true
